-- Allow manual order_number override (for year-based sync import)
-- GENERATED BY DEFAULT still auto-generates when no value is provided (e.g. QR scan)
ALTER TABLE work_orders
  ALTER COLUMN order_number SET GENERATED BY DEFAULT;

-- Function: get max order_number for a given year (uses existing completed_at index)
CREATE OR REPLACE FUNCTION get_max_order_number_for_year(target_year INT)
RETURNS BIGINT
LANGUAGE sql STABLE
AS $$
  SELECT COALESCE(MAX(order_number), 0)
  FROM work_orders
  WHERE completed_at >= make_date(target_year, 1, 1)::timestamptz
    AND completed_at < make_date(target_year + 1, 1, 1)::timestamptz;
$$;
